### ISSUE TITLE
[front] ユーザーの名前を設定できるようにする

### ISSUE THREAD

**Issue by mahiro72** [jphacks/F_2205#124]
### 内容

アワードデイいけたらやる

### TODO
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by KojimaNaoyuki** [comment]
## 残タスク
本番環境で十分にテストする
これの作成にあたり、エフェクトも改修をいれたので、そっちも

**Comment by KojimaNaoyuki** [comment]
完了
