### ISSUE TITLE
[front][server]エフェクト機能

### ISSUE THREAD

**Issue by KojimaNaoyuki** [jphacks/F_2205#164]
## 仕様
エフェクトボタンが押されると、指定のエフェクトがエフェクトを作動させたユーザーのビデオに5秒間の間映る。なめらかに表れ、なめらかに消える。

**Comment by KojimaNaoyuki** [comment]
## 残タスク
- バックエンドとの繋ぎ込み
  - 他ユーザーがエフェクトを起動したときの挙動
    - バックエンドから通知もらうタイミング(websocketConn.onmessage)でvideo.vueのeffectOthersメソッドを実行する。そうすることで、他ユーザーのビデオでエフェクトを作動させることができる
  - 自分がエフェクトを作動させた時
    - websocketでバックエンド側に通知し、バックエンドが全員に通知する

- エフェクトの種類を選択できるようにUI作成
- エフェクトの種類を充実させる
  - videoEffect.vueのid=videoId + -effectの中に適切に記述することで、エフェクトの種類を増やすことができる(waiwaiを参照)

**Comment by KojimaNaoyuki** [comment]
## バックエンド仕様案
- set_effect などタイプをもう一つ作る
- 誰かがset_effectをしたらそのタイミングで全員に通知が行く(websocket)
- フロントに送るデータは、誰が何番のエフェクトを起動したかを通知
  - エフェクトは起動したら5秒間で自動で消える仕様のため、継続的にその状態を維持しなくてよい。そのため、set_effectをしたタイミングで全員に通知されるwebsocket(type: set_effect )で送る「誰が何番のエフェクトを起動したか」のデータは必ず一つになる。なので、全てのユーザー毎に分けてレスポンスにする必要はない。

**Comment by KojimaNaoyuki** [comment]
## response

```
{
    "type": "SET_EFFECT",
    "info": {
        "from": "hoge1",
        "to": ""
    },
    "effect": {
        member: {
          name: hoge1
          effectNumber: 1
        }
    }
}
```

みたいな

**Comment by mahiro72** [comment]
ちょっと考えたいのでしばしお待ちを

**Comment by KojimaNaoyuki** [comment]
> エフェクトの種類を選択できるようにUI作成

完了

**Comment by KojimaNaoyuki** [comment]
完了
