### ISSUE TITLE
[front]視線検知でフォーカスの修正 フォーカス全解除周り

### ISSUE THREAD

**Issue by KojimaNaoyuki** [jphacks/F_2205#242]
## 内容
現在は画面外を10回見たらフォーカス全解除になっているが、それではリクエスト数が多くてwebsocketが落ちるため100回などもっとリクエスト数を減らす

**Comment by Fuyan777** [comment]
視線精度が悪いと，なかなかフォーカスされない...
50回でもなかなかうまくいかないので，悩み中

半分の25にするか
